# Build the site
[build]
  command = "DEBUG=* npx @11ty/eleventy"
  publish = "_site"

# Assign all the post-processing
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirect from the default Netlify site to my custom domain
[[redirects]]
  from = "https://frontroyalband.netlify.app/*"
  to = "https://www.frontroyalband.com/:splat"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-image-optim"

# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    Content-Security-Policy = "default-src 'self' https://www.frontroyalband.com https://d33wubrfki0l68.cloudfront.net https://bandcamp.com https://rest.bandsintown.com https://widget.bandsintown.com https://img.youtube.com/ https://www.youtube-nocookie.com/ data: 'unsafe-inline'"
